Translations = { 
    'ru': {
        'level_status' : 'Выберите уровень сложности: easy/normal/hard/impossible:',
        'stat_user' : 'Игрок | Попытки | Время',
        'stat_clue' : "Что бы вывести таблицу рекордов, введите 'stat'",
        'name' : 'Введите ваше имя: ',
        'start' : 'Добро пожаловать в игру, {}!',
        'record_status' : 'Текущий рекорд, который нужно побить: {} попыток.',
        'guess' : 'Введите число от 1 до {}:', 
        'range' : 'Число должно быть в диапазоне от 1 до {}!',
        'higher' : 'Число больше',
        'less' : 'Число меньше!',
        'numbers_only' : 'Введи ЦИФРЫ, бро.',
        'exit' : 'Нажмите Enter для выхода...',
        'attempts_1' : 'WTF! Ты чё Эпштейн? {} попыток даже мне не по зубам.',
        'attempts_7' : 'Браво босс! {} попыток, достойный результат.',
        'attempts_10' : 'Более менее, {} попыток, но все равно поздравляю.',
        'troll_start' : 'Эй чувак! Ты когда тест на IQ проходил ',
        'hood_troll' : 'Это район для крутых, проваливай!',
        'shame' : '{} попыток, позор!',
        'calling' : 'Звоним твоей маме!',
        'mom_answer' : 'Твоя мама: Вы серьезно? Я сейчас откажусь от него.',
        'quote' : 'You can always be thinner. Look Better. - P.Bateman',
        'look' : 'LOOK BETTER',
        'new_record' : 'Отлично, твой новый рекорд на {} попыток лучше.',
        'bad_record' : 'Бро, в прошлый раз ты был лучше. Твой лучший результат был {}.'
        
        },
    'en': {
        'level_status' : 'select difficulty level: easy/normal/hard/impossible:',
        'stat_user' : 'Users | Attempts | Time',
        'stat_clue' : "To display the high score table, enter 'stat'",
        'name' : 'Enter your name:',
        'start' : 'Welcome to the game, {}!',
        'record_status' : 'Current record to beat: {} attempts.',
        'guess' : 'Enter a number between 1 and {}: ',
        'range' : 'The number must be between 1 and {}!',
        'higher' : 'The number is higher!',
        'less' : 'The number is less!',
        'numbers_only' : 'Enter the NUMBERS, bro.',
        'exit' : 'Press Enter to exit...',
        'attempts_1' : 'WTF! Are you Einstein? Even I can`t guess in {} attempts.',
        'attempts_7' : 'Bravo boss! {} attempts, a worthy result.',
        'attempts_10' : 'More or less, {} attempts, but still congratulations!',
        'troll_start' : 'Hey, dude! When did you get your IQ tested?',
        'hood_troll' : 'This is a cool neighborhood, get lost!',
        'shame' : '{} attempts, shame!',
        'calling' : "We're calling your mom!",
        'mom_answer' : "Your mom: Are you serious? I'll give him up right now.",
        'quote' : 'You can always be thinner. Look Better. - P.Bateman',
        'look' : 'LOOK BETTER',
        'new_record' : 'Cool, Your new record is {} attempts better.',
        'bad_record' : 'Bro, you were better last time. Your best was {}.',
    },
    'uk': {
        'level_status': 'Оберіть рівень складності: easy/normal/hard/impossible:',
        'stat_user': 'Гравець | Спроби | Час',
        'stat_clue': "Щоб вивести таблицю рекордів, введіть 'stat'",
        'name': 'Введіть ваше ім’я: ',
        'start': 'Ласкаво просимо до гри, {}!',
        'record_status': 'Поточний рекорд, який треба побити: {} спроб.',
        'guess': 'Введіть число від 1 до {}:',
        'range': 'Число має бути в діапазоні від 1 до {}!',
        'higher': 'Число більше',
        'less': 'Число менше!',
        'numbers_only': 'Вводь ЦИФРИ, бро.',
        'exit': 'Натисніть Enter для виходу...',
        'attempts_1': 'WTF! Ти що, Эйнштейн? {} спроб навіть мені не по зубах.',
        'attempts_7': 'Браво, бос! {} спроб, гідний результат.',
        'attempts_10': 'Більш-менш, {} спроб, але все одно вітаю.',
        'troll_start': 'Гей, чувак! Ти коли тест на IQ проходив? ',
        'hood_troll': 'Це район для крутих, забирайся звідси!',
        'shame': '{} спроб, ганьба!',
        'calling': 'Дзвонимо твоїй мамі!',
        'mom_answer': 'Твоя мама: Ви серйозно? Я зараз відмовлюся від нього.',
        'quote': 'You can always be thinner. Look Better. - P.Bateman',
        'look': 'LOOK BETTER',
        'new_record': 'Чудово, твій новий рекорд на {} спроб кращий.',
        'bad_record': 'Бро, минулого разу ти був кращим. Твій найкращий результат був {}.'
    },
    'jp': {
        'level_status': '難易度を選択してください (easy/normal/hard/impossible):',
        'stat_user': 'プレイヤー | 試行回数 | 時間',
        'stat_clue': "ランキングを表示するには 'stat' と入力してください",
        'name': '名前を入力してください: ',
        'start': 'ようこそ、{}！',
        'record_status': '現在の記録：{} 回。これを超えてみろ！',
        'guess': '1から {} までの数字を入力してください:',
        'range': '1から {} までの範囲で入力してください！',
        'higher': 'もっと大きい数字です',
        'less': 'もっと小さい数字です！',
        'numbers_only': '数字を入力しろ、ブラザー。',
        'exit': 'Enterを押して終了...',
        'attempts_1': 'なんだって！あれはアインシュタインか？俺が何回やってもあんなことはできないよ。',
        'attempts_7': 'ブラボー、ボス！ {} 回か、見事な結果だ。',
        'attempts_10': 'まあまあだな。 {} 回。とりあえずおめでとう。',
        'troll_start': 'おいおい！IQテストいつ受けたんだ？ ',
        'hood_troll': 'ここはタフな奴らの縄張りだ。失せろ！',
        'shame': '{} 回だと？恥を知れ！',
        'calling': 'お前のママに電話中...',
        'mom_answer': 'ママ：マジで？もうあの子の親やめるわ。',
        'quote': 'You can always be thinner. Look Better. - P.Bateman',
        'look': 'もっと上を目指せ',
        'new_record': 'お見事！自己ベストを {} 回更新したぞ。',
        'bad_record': 'おい、前回の方がマシだったぞ。お前のベストは {} 回だ。'
    }
      
}
